// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5eO574DfRR18wUeO49zqeerwzp9wgQRw',
    appId: '1:848446032391:web:c45fe2a58a4ca9b073f8a2',
    messagingSenderId: '848446032391',
    projectId: 'findmua-462b6',
    authDomain: 'findmua-462b6.firebaseapp.com',
    storageBucket: 'findmua-462b6.appspot.com',
    measurementId: 'G-GSSLWL708Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzqj05zXH-LmNkPJ094t0oVpUL-cGct6A',
    appId: '1:848446032391:android:82d88d581d0b5a5673f8a2',
    messagingSenderId: '848446032391',
    projectId: 'findmua-462b6',
    storageBucket: 'findmua-462b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkv8bgkrUc2ojB9tGMbV37ePT-OL_Tc7Q',
    appId: '1:848446032391:ios:25853b11677d1bfa73f8a2',
    messagingSenderId: '848446032391',
    projectId: 'findmua-462b6',
    storageBucket: 'findmua-462b6.appspot.com',
    iosBundleId: 'com.example.findmua',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkv8bgkrUc2ojB9tGMbV37ePT-OL_Tc7Q',
    appId: '1:848446032391:ios:25853b11677d1bfa73f8a2',
    messagingSenderId: '848446032391',
    projectId: 'findmua-462b6',
    storageBucket: 'findmua-462b6.appspot.com',
    iosBundleId: 'com.example.findmua',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5eO574DfRR18wUeO49zqeerwzp9wgQRw',
    appId: '1:848446032391:web:5c55938121cb193273f8a2',
    messagingSenderId: '848446032391',
    projectId: 'findmua-462b6',
    authDomain: 'findmua-462b6.firebaseapp.com',
    storageBucket: 'findmua-462b6.appspot.com',
    measurementId: 'G-H3KGBSZV1E',
  );
}
